---
- name: Dependencies / Ensure packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ required_packages }}"

- name: Dependencies / Ensure latest version of Rake
  gem:
    name: rake
    state: latest
