---
- name: Dependencies / Ensure packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - redmine
    - redmine-pgsql
    - ruby-all-dev
    - yard
    - gcc
    - g++
    - libmagick++-dev
    - cmake

- name: Dependencies / Ensure latest version of Rake
  gem:
    name: rake
    state: latest
