---
- include: tasks/dependencies.yml

- include: tasks/permissions.yml

- include: tasks/database.yml
  become: true
  become_user: postgres

- include: tasks/configuration.yml

- include: tasks/plugins.yml

- include: tasks/themes.yml

- include: tasks/setup.yml
