---
- name: Permissions / Ensure Redmine group
  group:
    name: "{{ redmine_username }}"
    state: present

- name: Permissions / Ensure Redmine system user
  user:
    name: "{{ redmine_username }}"
    groups: "{{ redmine_username }},crontab"
    system: true
    append: true
    home: "{{ home_path }}"
  notify: appserver reload

- name: Permissions / Ensure correct recursive mod & owner over directories
  file:
    path: "{{ item }}"
    owner: "{{ redmine_username }}"
    group: "{{ redmine_username }}"
    mode: "u+rwX,g+rwX,o-rwX"
    recurse: true
  with_items:
    - "{{ storage_path }}"
    - "{{ config_path }}"
  notify: appserver reload

- name: Permissions / Ensure correct non-recursive owner over files
  file:
    path: "{{ item }}"
    owner: "{{ redmine_username }}"
    group: "{{ redmine_username }}"
  with_items:
    - "{{ cache_path }}"
    - "{{ gemfile_lock_path }}"
    - "{{ home_path }}"
  notify: appserver reload
