---
- name: Plugins / Ensure plugins directory
  file: path=/usr/share/redmine/plugins/ state=directory mode=0755

- name: Plugins / Ensure enabled plugins present
  with_items: "{{ redmine_plugins_enabled }}"
  loop_control:
    loop_var: plugin
  include_role:
    name: gitpush-deploy
  vars:
    gitpush_local_repo_path: "redmine_plugins/{{ plugin }}/.git/"
    gitpush_repo_path: "/usr/share/redmine/plugins/{{ plugin }}/.git/"
    gitpush_workdir_path: "/usr/share/redmine/plugins/{{ plugin }}/"
  notify: appserver reload

- name: Plugins / Ensure required gems
  bundler:
    state: present
    chdir: /usr/share/redmine/
  notify: appserver reload

- name: Plugins / Make Redmine user owner of plugins files
  file:
    path: "/usr/share/redmine/plugins/"
    owner: "{{ redmine_username }}"
    group: "{{ redmine_username }}"
    recurse: true
  notify: appserver reload
