---
- name: Setup / rake
  command: "bin/rake {{ item }} chdir={{ source_path }}"
  with_items:
    - db:migrate
    - redmine:plugins:migrate
    - assets:precompile
    - tmp:clear
  environment:
    RAILS_ENV: "{{ redmine_rails_environment }}"
  register: response
  changed_when: response.stdout not in ['rubycritic failed.', '']
  notify: appserver reload

- name: Setup / inbound mail cronjob
  cron:
    name: inbound mail
    user: "{{ redmine_username }}"
    minute: "*/{{ redmine_mail_pop3_refresh_minutes }}"
    job: >
      cd {{ source_path }} &&
      {{ source_path }}/bin/rake
      redmine:email:receive_pop3
      RAILS_ENV={{ redmine_rails_environment }}
      host="{{ redmine_mail_pop3_host }}"
      port="{{ redmine_mail_pop3_port }}"
      username="{{ redmine_mail_pop3_username }}"
      password="{{ redmine_mail_pop3_password }}"
      apop={{ redmine_mail_pop3_apop|bool()|lower }}
      ssl={{ redmine_mail_pop3_ssl|bool()|lower }}
      >> /dev/null
  when: "{{ redmine_mail_pop3_enable }}"
